---
- hosts: localhost

  tasks: 
     - name: Instala docker-compose
       yum: 
          name: 
              - docker-compose
          state: present

     - name: REPO Docker - Configurado
       yum_repository:
           baseurl: http://download.docker.com/linux/centos/7/x86_64/stable/ 
           enabled: yes
           name: docker
           description: docker-ce
           state: present

     - name: REPO Centos - Configurado
       yum_repository:
           baseurl: http://mirror.centos.org/centos/7/os/x86_64/
           enabled: yes
           name: centos
           description: centos
           state: present

     - name: REPO Centos Extras - Configurado
       yum_repository:
           baseurl: http://mirror.centos.org/centos/7/extras/x86_64/ 
           enabled: yes
           name: centos-extras
           description: centos-extras
           state: present

     - name: RPM KEY CENTOS - Instalada
       rpm_key: 
             key: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7
             state: present

     - name: RPM KEY DOCKER - Instalada
       rpm_key: 
             key: https://download.docker.com/linux/centos/gpg
             state: present 

     - name: Docker - Instalado
       yum:  
         name: 
            - docker-ce.x86_64
            - docker-ce-cli.x86_64
            - docker-ce-selinux.noarch
            - git
            - vim
            - libselinux-python3.x86_64
         state: present 

     - name: Docker - Iniciado
       service: 
           name: docker
           state: started
           enabled: yes 
      
     - name: AWX - Descarga 
       unarchive:
         src: https://github.com/ansible/awx/archive/refs/tags/17.1.0.tar.gz
         dest: ./ 
         remote_src: yes       
   
     - name: AWX - Admin Password configurado
       lineinfile: 
             regex: "^# admin_password"
             path: /root/deploy-awx/awx-17.1.0/installer/inventory
             line: "admin_password=password" 
 
